version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:16.1
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    restart: unless-stopped