INSERT INTO CATEGORY_DISHES (NAME) values ('BREAKFAST');
INSERT INTO DISHES (NAME, PRICE, CATEGORY_ID) values ('OMLET', 10, 1);
INSERT INTO DISHES (NAME, PRICE, CATEGORY_ID) values ('SANDWICH', 10.45, 1);
